services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: devzoku-client
    restart: unless-stopped
    env_file: ./client/.env
    ports:
      - "3000:3000"
    networks:
      - devzoku
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: devzoku-server
    env_file: ./server/.env
    ports:
      - "8000:8000"
    networks:
      - devzoku
    depends_on:
      - postgres
      - valkey
      - qdrant

  migrator:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: builder
    environment:
      - DATABASE_URL=postgresql://sneha:sneha@postgres:5432/DevZoku-db
    depends_on:
      - postgres
    command: bun run db:push
    networks:
      - devzoku
    restart: "no"

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: devzoku-worker
    restart: unless-stopped
    command: bun worker
    env_file: ./server/.env
    networks:
      - devzoku
    depends_on:
      - server

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: devzoku-db
    restart: always
    environment:
      POSTGRES_DB: DevZoku-db
      POSTGRES_USER: sneha
      POSTGRES_PASSWORD: sneha
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devzoku

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - devzoku
    depends_on:
      - postgres

  valkey:
    image: valkey/valkey:8.1.3-alpine3.22
    container_name: devzoku-valkey
    ports:
      - 6379:6379
    restart: always
    volumes:
      - valkey_data:/data
    networks:
      - devzoku

  qdrant:
    image: qdrant/qdrant
    container_name: devzoku-qdrant
    ports:
      - 6333:6333
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - devzoku

networks:
  devzoku:
    driver: bridge

volumes:
  postgres_data:
  valkey_data:
  qdrant_data:
