export const hackathonTags = {
  techStacks: [
    "Web3",
    "AI",
    "Machine Learning",
    "Deep Learning",
    "Blockchain",
    "Cloud Computing",
    "DevOps",
    "AR/VR",
    "IoT",
    "Cybersecurity",
    "Data Science",
    "Big Data",
    "Mobile Development",
    "Android",
    "iOS",
    "Game Development",
    "Full Stack",
    "Frontend",
    "Backend",
  ],

  toolsAndFrameworks: [
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "MongoDB",
    "Firebase",
    "PostgreSQL",
    "Supabase",
    "Tailwind CSS",
    "Django",
    "Flask",
    "FastAPI",
    "LangChain",
    "TensorFlow",
    "PyTorch",
    "Solidity",
    "Figma",
    "GitHub",
    "Docker",
    "Kubernetes",
  ],

  domainsAndIndustries: [
    "Fintech",
    "Healthcare",
    "EdTech",
    "AgriTech",
    "ClimateTech",
    "Sustainability",
    "Social Good",
    "E-Commerce",
    "Smart Cities",
    "LegalTech",
    "Entertainment",
    "Gaming",
    "TravelTech",
    "FoodTech",
    "HRTech",
  ],

  themesAndChallenges: [
    "Accessibility",
    "Open Innovation",
    "Rapid Prototyping",
    "Beginner Friendly",
    "Women in Tech",
    "Student-Focused",
    "Team Collaboration",
    "Innovation Challenge",
    "Startup Ideas",
    "Scale-Ready Solutions",
  ],

  advancedTech: [
    "LLMs",
    "NLP",
    "ZK Proofs",
    "Smart Contracts",
    "Serverless",
    "Edge Computing",
    "Multimodal AI",
    "Prompt Engineering",
    "AI Safety",
    "Open Source",
  ],
};

export const tagSections = [
  { label: "Tech Stacks", tags: hackathonTags.techStacks },
  { label: "Tools & Frameworks", tags: hackathonTags.toolsAndFrameworks },
  { label: "Domains & Industries", tags: hackathonTags.domainsAndIndustries },
  { label: "Themes & Challenges", tags: hackathonTags.themesAndChallenges },
  { label: "Advanced Tech Buzzwords", tags: hackathonTags.advancedTech },
];
